### ISSUE TITLE
Allow late pause to let lighting set up

### ISSUE THREAD

**Issue by SteveTownsend** [SteveTownsend/PauseAfterLoadUnscripted#14]
Nexus request

> this somehow messes with my enb or lux in a way that everything seems overly bright before the shaders kick in. could you add an option to the ini in which it will pause the game after 0.5 seconds or something? so the light gets properly loaded before pausing? 

It could be possible to allow toggling of delay based on a hotkey for a period after a transition, which could remove the need for 'always delay'

**Comment by ra2phoenix** [comment]
I noticed this too, I don't know if it's blocking ENB Helper from passing the weather ini to ENB or something else, but it's like ENB is off or on default settings until I move to unpause.  Could also be pausing ELVASS, but the issue appears indoors as well.

**Comment by SteveTownsend** [comment]
For investigation

**Comment by SteveTownsend** [comment]
Added a delay, not sure it makes any difference though. More testing needed.

**Comment by SteveTownsend** [comment]
putting this out for testing in v1.2.0, resolve for now
